name: Build and Deploy

on:
  push:
    branches:
      - develop

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "actions@users.noreply.github.com" && git config --global user.name "GitHub Actions"

      - name: Push changes to main
        run: |
          git checkout main
          git config pull.rebase false
          git pull origin develop  # Garante que estamos atualizados com a branch develop
          git add index.html  # Supondo que index.html é o arquivo gerado
          git commit -m "Update index.html from develop branch"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

