name: Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install jinja2

      - name: Generate HTML and Read Markdown
        run: |
          cd src/
          python CriarBlog.py

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Auto-commit changes"
          git push # Push changes to 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Este job depende do job 'build'
    if: ${{ needs.build.result == 'success' }}  # Executar apenas se o job 'build' tiver sucesso
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "actions@users.noreply.github.com" && git config --global user.name "GitHub Actions"

      - name: Push changes to main
        run: |
          git remote update
          git fetch
          git pull
          git checkout main
          git checkout develop -- index.html
          git add .
          git commit -m "Atualizando index.html"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

