name: Copy Index to Main After Build

on:
  workflow_run:
    workflows: ["Build Develop Branch"]
    branches:
      - develop
    types:
      - completed

jobs:
  copy-index:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy index.html to main
        run: |
          git checkout main
          git checkout develop -- index.html
          git config user.name "GitHub Actions"
          git config user.email "<YOUR_EMAIL>@example.com"
          git add index.html
          git commit -m "Copying index.html from develop to main by GitHub Actions"
          git push origin main
